spring:
  application:
    name: ibissupply-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/ibissupply
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:1234}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

server:
  port: 8080

jwt:
  secret: ${JWT_SECRET:ibissupply-secret-key-minimum-256-bits-long-for-hs256}
  expiration: 900000        # 15 minutes in ms
  refresh-expiration: 604800000  # 7 days in ms

logging:
  level:
    com.ibissupply: DEBUG
    org.springframework.security: WARN
    org.web3j: WARN

ai:
  enabled: true
  base-url: http://localhost:8000

groq:
  api-key: ${GROQ_API_KEY:}

blockchain:
  enabled: true
  rpc-url: http://localhost:8545
  chain-id: 31337
  private-key: ${BLOCKCHAIN_PRIVATE_KEY:0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80}
  addresses:
    batch-registry: "0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512"
    shipment-registry: "0x9fE46736679d2D9a65F0992F2272dE9f3c7fa6e0"
    quality-registry: "0xCf7Ed3AccA5a467e9e704C703E8D87F634fB0Fc9"
    farm-registry: "0xDc64a140Aa3E981100a9becA4E685f962f0cF6C9"
    certificate-nft: "0x5FC8d32690cc91D4c39d9d3abcBD16989F875707"
